### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by nilskp** [gnieh/diffson#148]
I'm trying to use another Json parser, but keep running into things that don't work. The README states:

> If you want to add support for your favorite Json library, you may only depend on diffson core module `diffson-core` and all you need to do then is to implement the `diffson.DiffsonInstance` class

But there's no `DiffsonInstance` class anywhere. And implementing `Jsony` is insufficient, even though it's also stated that:

> it is possible to use it with any json library of your liking. The only requirement is to have a `Jsony` for your json library

And an example of how to serialize a `Diff` (`ops: List[Operation[_]]`) would be nice. :-)

**Comment by satabin** [comment]
Hi,

This first one is indeed a leftover from version 3, things were renamed. I will update the documentation.

Fr the second problem, implmenting a `Jsony` is sufficient for using diffson. The version 4 doesn't say anything about (de)serializing patches because it was out of the scope of the library and is heavily dependent on the Json library you are using. When you say it "is insufficient" what do you mean? Do you have compilation error?

**Comment by satabin** [comment]
I added a section on (de)serialization in the README, and fixed the occurrence of `DiffsonInstance`.
