### ISSUE TITLE
Ignore methods on patch?

### ISSUE THREAD

**Issue by ryantheleach** [gnieh/diffson#15]
Hey, I'm pleased to see that this project exists!

What do you think about adding a way to ignore changes at a certain path?

So one usecase for this is to track changes to JSON replies from web services, but things like timestamps or xsrf tokens which are going to be different every test, but can be safely ignored in the patch as it's data that is changing and not the structure?

Do you understand what I mean? Sorry if I'm not making myself clear.

**Comment by satabin** [comment]
Hi, I'm pleased you use and enjoy diffson :)

I think I know what you mean. I would suggest the addition of `filter` and `filterNot?` methods on class `JsonPatch`, which filter the operations given a predicate. Currently you can do it like this:

```scala
val p1 = json1.diff(json2)
val p2 = JsonPatch(p1.ops.filterNot(op => op.path == List("my", "path", "to", "ignore")))
```

Is that what you want?

**Comment by ryantheleach** [comment]
Cheers, I probably should have looked into it further before creating an issue. this fits my needs. Unsure if you would want to add any further sugar to this, but I can create functions / use enrich my library if necessary. Thanks.

**Comment by satabin** [comment]
I think that seeing a patch as a collection of operations is good. Therefore, I will add typical collection methods (`map`, `flatMap`, `filter`, `withFilter`, `foldLeft`, `foldRight` and `foreach` at least) so that it can be handled as a collection. These will be simple proxies for the underlying operation list methods,it makes it more convenient to use. I think they will be available implicitly through specific object  so that you only import the methods you need.
