### ISSUE TITLE
Get Json Diff

### ISSUE THREAD

**Issue by darkfrog26** [gnieh/diffson#53]
diffson is a very powerful library, but there does not seem to be any way to take two `Json` instances and derive a `Json` instance that contains *only* the changes between the two.

**Comment by satabin** [comment]
What do you mean exactly? A `JsonPatch` is a json object containing only the changes.

**Comment by darkfrog26** [comment]
@satabin yes, but how do I get `Json` from that like `patch` does, but only the differences, not the merged `Json`.

**Comment by satabin** [comment]
I really do not understand, do you have a concrete example of 2 json objects and what you expect to get out of it?

**Comment by darkfrog26** [comment]
For example, if I have:

```
{
  "a": 1,
  "b": 2,
  "c": 3
}
```

and:

```
{
  "a": 1,
  "b": 3
}
```

I'd like the resulting Json to be:

```
{
  "b": 3,
  "c": null
}
```

**Comment by darkfrog26** [comment]
For better clarification, this is for a document database that I want to only send the changes to the document, not the entire document again.

**Comment by satabin** [comment]
`null` sounds quite arbitrary to me. And a `JsonPatch` is exactly describing the changes. In your example you would get

```json
[
  {
    "op": "replace",
    "path": "/b",
    "value": 3
  },
  {
    "op": "delete",
    "path": "/c"
  }
]
```

These are exactly the changes to apply to the first document to get the second one.

**Comment by darkfrog26** [comment]
@satabin I understand that, but how do I go from the `JsonPatch` to the diff `Json` I want?

**Comment by satabin** [comment]
There is no generic way. You may decide in your application that deletion is equivalent to setting to `null`, In any way, this is not the purpose of the core diffson library, which aims at diffing json objects and producing patches according to the RFC. You could write a kind of _patch interpreter_ in your application that produces the object you want from the standard operations.

But in both cases, what you will send to your database is a patch object, either in the RFC format or in your own one. On the document database side, you’ll still have to interpret the received object to construct the target value. Is the format you want to have something built-in in your database? If yes, do you have any pointer so that I can have a better idea of what you want to achieve?

The advantages of using the `JsonPatch` are that it is a standardized way of describing json patches, it has a clearly defined semantics, allows for checking contracts on json objects, has more chance to be already implemented by other products.

**Comment by darkfrog26** [comment]
My example above is exactly what I'm trying to achieve. Simply taking two circe `Json` instances and creating a new `Json` instance containing only the delta. I suppose I can write my own system to process `Operation` instances on a `JsonPatch` to generate `Json` instance from the patch but was hoping that diffson would make such a thing a little easier.

**Comment by satabin** [comment]
It cannot, because the format you need is ambiguous in the general case. `null` is a valid json value, and setting to null does not (in the general case) mean deleting a path.
Diffson helps you diffing objects, provide a json instance containing only the delta (a json patch), but what you want is another patch format. This is not the purpose of diffson, but you can save you the trouble of making a diff and then transforming the results to your format. I would not recommend it, though.

What can’t you use the standard patch format in your document database? What database are you using? How would you handle your document format on the database side?

**Comment by darkfrog26** [comment]
In fact, this is exactly what I want: https://github.com/agourlay/cornichon/blob/c2e0974ac2a27dc973e0a3ffdc8520ea55b6effe/src/main/scala/com/github/agourlay/cornichon/json/JsonDiff.scala

However, it is somewhat buggy.

**Comment by darkfrog26** [comment]
@satabin here's the exact use-case: https://docs.arangodb.com/3.1/HTTP/Gharial/Vertices.html#modify-a-vertex

**Comment by satabin** [comment]
For resolution: as discussed on gitter, I added a way not to be smart about array diffs in diffson (see PR #54) and the generated diffs should be easy to convert to the required format on the client side.

I consider this issue closed.
