### ISSUE TITLE
NumberFormatException with path of more than 10 digits

### ISSUE THREAD

**Issue by kristian-lange** [gnieh/diffson#84]
I updated "diffson-play-json_2.11" from 2.1.0 to 3.1.1. Now I have a weird behaviour in `JsonPatch.parse`.

If I use a path with more than 10 digits, like 
```
JsonPatch.parse("""[{"op":"add","path":"/12345678901","value":{"msg":"foo"}}]""")
```
I get `java.lang.NumberFormatException`, but not with either less digits or an additional letter
```
JsonPatch.parse("""[{"op":"add","path":"/1234567890","value":{"msg":"foo"}}]""")
JsonPatch.parse("""[{"op":"add","path":"/a12345678901","value":{"msg":"foo"}}]""")
```

Any advice how to fix this?

**Comment by satabin** [comment]
Hi,

This number overflows the `Int` capacity, used by Play Json to index arrays (underlying Scala type is `IndexedSeq`), so there is no way this can be parsed by Play Json.

In the second case, removing digits makes it a valid integer, or because you add a letter, it is not an array index but an object field name, which is not a number but can be any string (basically objects are represented as `Map[String, JsValue]`).

**Comment by kristian-lange** [comment]
Ok, I wasn't aware that the path is treated as an array index in case of a path with digits only. Thank you!

**Comment by satabin** [comment]
I could be smarter about it, and parse it as string if it is not a valid int. That would allow for arbitrary long number object keys. Would this help in your case?

**Comment by satabin** [comment]
FYI #89

**Comment by kristian-lange** [comment]
But wouldn't this (parse it as string if it is not a valid int) be against the JSON patch standard?

**Comment by satabin** [comment]
Nope, because it should only be interpreted as an index in the context of an array cell access. The RFC is not strongly typed in that regard, so a number in a pointer might also be interpreted as an object field.
