### ISSUE TITLE
for play json: validation type JsResult throws JsResultException

### ISSUE THREAD

**Issue by Bo3gyX** [gnieh/diffson#92]
example:
```scala
val str =
    """
      |[{"op_no_correct":"replace","path":"/somePath","value":"xxx"}]
    """.stripMargin

 Json.parse(str).validate[JsonPatch[JsValue]] match {
    case JsSuccess(d, _) =>
      println("Success")
    case JsError(_) =>
      println("Error")
  }
```

should be processed correctly in pattern matching, but this does not happen, and an exception occurs.
it seems that the problem is here:

https://github.com/gnieh/diffson/blob/master/playJson/shared/src/main/scala/diffson/playJson/DiffsonProtocol.scala#L170

P.S.
Sorry for my english i use translator.

**Comment by satabin** [comment]
Hi,

This is the expected behavior with the implementation you pointed out, because `as[T]` returns a `T` or throws an exception.

It is a bit weird that play-json does not have a _safe_ version of `as` that returns a `JsResult`. I am not a big expert (or even fan) of the play-json API, but I guess we could rewrite it to be safer by first validating each `op` as an `Operation[JsValue]`. I will give it a shot.

**Comment by satabin** [comment]
Ok, so `validate` is the _safe `as`_ I was thinking about, I got confused by the name... I will switch to that.

**Comment by satabin** [comment]
Published in last `0.4.0-SNAPSHOT`. Your code now works I you expect it.

**Comment by Bo3gyX** [comment]
thank you very much, I will wait for release

**Comment by satabin** [comment]
Version 4.0.0-M3 is now available, let me know if it works for you.
